---
- name: Setup nginx with SSL and mariadb
  hosts: nodes
  become: true
  tasks:
    - name: Setup nginx server with tls
      block:
        - name: SSL setup
          import_role:
            name: cert_role

        - name: Nginx setup
          import_role:
            name: nginx_role
      tags:
        - nginx

    - name: Mariadb setup
      import_role:
        name: mariadb_role
      tags:
        - mariadb

    - name: Wordpress setup
      import_role:
        name: wordpress_role

    - name: Php setup
      import_role:
        name: php_role

  post_tasks:
    - name: Check https
      uri:
        url: "https://{{ ansible_host }}:{{ nginx_tls_port }}"
        return_content: true
        validate_certs: false
      connection: local
      register: example_webpage_out
      failed_when: example_webpage_out.status != 200
