---
- name: Setup nginx with SSL and mariadb
  hosts: nodes
  become: true
  tasks:
    - name: Setup nginx server with tls
      block:
        - name: SSL setup
          import_role:
            name: cert-role

        - name: Nginx setup
          import_role:
            name: nginx-role
      tags:
        - nginx

    - name: Mariadb setup
      import_role:
        name: mariadb-role
      tags:
        - mariadb

  post_tasks:
    - name: Check web site from control server
      block:
        - name: Check http
          uri:
            url: "http://{{ ansible_host }}:{{ nginx_port_no_tls }}"
            return_content: true
          connection: local
          register: example_webpage_out
          failed_when: example_webpage_out.status != 200
          tags:
            - nginx

        - name: Check https
          uri:
            url: "https://{{ ansible_host }}:{{ nginx_port_tls }}"
            return_content: true
            validate_certs: false
          connection: local
          register: example_webpage_out
          failed_when: example_webpage_out.status != 200
      tags:
        - nginx
