---
- name: setup nginx with ssl and mariadb
  hosts: nodes
  become: true
  tasks:
    - name: ssl setup
      import_role:
        name: cert-role
      tags:
        - cert

    - name: nginx setup
      import_role:
        name: nginx-role
      tags:
        - nginx

    - name: mariadb setup
      import_role:
        name: mariadb-role
      tags:
        - mariadb

  post_tasks:
    - name: check web site-http from control server
      uri:
        url: "http://{{ ansible_host }}:{{ nginx_port_no_tls }}"
        return_content: true
      connection: local
      register: example_webpage_out
      failed_when: example_webpage_out.status != 200
