---
- name: test
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    mac1: "482056876429"
    mac2: 00C9DEF21521
    mac3: 01caDEF29501
  tasks:
    - name: mac filter
      debug:
        msg: "{{ mac1 | mac_filter }}"
    - name: mac filter
      debug:
        msg: "{{ mac2 | mac_filter }}"
    - name: mac filter
      debug:
        msg: "{{ mac3 | mac_filter }}"
