---
- name: install php-fpm packages and wordpress
  hosts: nodes
  vars_files:
    - vars/main.yaml
  become: true
  tasks:
    - name: Copy nginx configuration from template for wordpress
      template:
        src: templates/nginx-wordpress.conf.j2
        dest: /etc/nginx/conf.d/nginx-wordpress.conf
        owner: root
        group: root
        mode: 0644
      notify: restart nginx

    - name: Put repo files to /etc/yum.repos.d/ directory
      copy:
        src: "files/{{ item }}"
        dest: /etc/yum.repos.d/
        owner: root
        group: root
        mode: 0644
      with_items:
        - epel.repo
        - remi-php74.repo
        - remi-safe.repo

    - name: Install packages from 'php_packages_list'
      yum:
        name: "{{ php_packages_list }}"

    - name: Remove default /etc/php-fpm.d/www.conf file
      file:
        path: /etc/php-fpm.d/www.conf
        state: absent

    - name: Copy wordpress.conf from files to /etc/php-fpm.d/wordpress.conf
      copy:
        src: files/wordpress.conf
        dest: /etc/php-fpm.d/wordpress.conf
        owner: root
        group: root
        mode: 0644

    - name: >
        Download WordPress from http://wordpress.org/wordpress-{{ wp_version }}.tar.gz
        to /srv/ folder + checksum
      get_url:
        url: "http://wordpress.org/wordpress-{{ wp_version }}.tar.gz"
        dest: "/srv/wordpress.tar.gz"
        checksum: "{{ wp_checksum }}"

    - name: Unarchive wordpress to /srv folder
      unarchive:
        src: "/srv/wordpress.tar.gz"
        dest: "/srv"
        remote_src: true

    - name: Add linux group "wordpress"
      group:
        name: wordpress

    - name: >
        Add linux user "wordpress" with group "wordpress"
        and /srv/wordpress as homedir
      user:
        name: wordpress
        group: wordpress
        home: /srv/wordpress

    - name: Create mariadb database for wordpress
      mysql_db:
        name: "{{ wp_db_name }}"

    - name: Create WordPress database user
      mysql_user:
        name: "{{ wp_db_user }}"
        password: "{{ wp_db_password }}"
        priv: "{{ wp_db_user }}.*:ALL"
      no_log: true

    - name: >
        Copy WordPress config file from templates
        to /srv/wordpress/wp-config.php
      template:
        src: templates/wp-config.php
        dest: /srv/wordpress/wp-config.php

    - name: >
        /srv/wordpress directory recursive rights
        for wordpress user and group
      file:
        path: /srv/wordpress
        owner: wordpress
        group: wordpress
        recurse: true
        mode: 0644

    - name: Start php-fpm Service
      service:
        name: php-fpm
        state: started
        enabled: true

  handlers:
    - name: restart php-fpm
      service:
        name: php-fpm
        state: restarted

    - name: restart nginx
      service:
        name: nginx
        state: restarted
