# ansible-playbook main.yaml --ask-vault-pass
---
- name: add users to remote host
  hosts: nodes
  gather_facts: false
  vars_files:
    - users.yaml
  tasks:
    - name: add user
      become: true
      ansible.builtin.user:
        name: "{{ user.name }}"
        comment: Ansible-generated user
        password: "{{ user.password | password_hash('sha512') }}"
      loop: "{{ users }}"
      loop_control:
        loop_var: user
        pause: 5
      no_log: true