# ansible-galaxy collection install community.mysql
---
- name: install MariaDB
  hosts: nodes
  vars_files:
    - vars/main.yaml
  become: true
  tasks:
    - name: Install 'mariadb-server' and 'MySQL-python' packages
      yum:
        name: 
          - mariadb-server
          - MySQL-python

    - name: Ensure 'mariadb' service is started and enabled
      service:
        name: mariadb
        state: started
        enabled: true

    - name: Create "{{ db_name }}" database
      mysql_db:
        name: "{{ db_name }}"

    - name: >
        Create database user "{{ db_user }}" with "{{ db_password }}"
        and "{{ db_name }}".*:ALL privelege
      mysql_user:
        name: "{{ db_user }}"
        password: "{{ db_password }}"
        priv: "{{ db_name }}.*:ALL"
      no_log: true