---
# tasks file for mariadb-role
- name: Install 'mariadb-server' and 'MySQL-python' packages
  yum:
    name:
      - mariadb-server
      - MySQL-python

- name: Ensure 'mariadb' service is started and enabled
  service:
    name: mariadb
    state: started
    enabled: true

- name: Create mariadb database for wordpress
  mysql_db:
    name: "{{ wp_db_name }}"

- name: Create WordPress database user
  mysql_user:
    name: "{{ wp_db_user }}"
    password: "{{ wp_db_password }}"
    priv: "{{ wp_db_user }}.*:ALL"
  no_log: true
